name: checkbox-gfx
summary: Checkbox tests for testing graphics
description: |
  Collection of tests to be run on devices to test graphics functionality
version: '1.0'
confinement: classic
grade: stable

base: core24

# Different apps that can be run by: checkbox-gfx.<app>
# Map to a script in bin/

apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper
  configure:
    command-chain: [bin/wrapper_local]
    command: bin/configure
  test:
    command-chain: [bin/wrapper_local]
    command: bin/test
  test-lvl-zero:
    command-chain: [bin/wrapper_local]
    command: bin/test-lvl-zero
  test-lvl-zero-rt:
    command-chain: [bin/wrapper_local]
    command: bin/test-lvl-zero-rt
  test-mesa:
    command-chain: [bin/wrapper_local]
    command: bin/test-mesa
  remote-slave:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper slave
    daemon: simple
    restart-condition: always
  shell:
    command-chain: [bin/wrapper_local]
    command: bin/shell-wrapper
  install:
    command: bin/install
  remove:
    command: bin/remove

passthrough:
  hooks:
    configure:
      command-chain: [bin/wrapper_local]

parts:
  checkbox-provider-gfx:
    plugin: dump
    source: ./checkbox-provider-gfx
    source-type: local
    build-snaps:
      - checkbox-provider-tools
      - checkbox24
    stage-packages:
      - python3-tinydb
      - python3-filelock
      - intel-gpu-tools
  bin:
    plugin: dump
    source: bin/
    organize:
      '*': bin/
  config-variables:
    plugin: dump
    source: config/

